gkn0672/CSIT314-CinemaBookingSystem

- requirements.txt
Reverts gkn0672/CSIT314-CinemaBookingSystem#65
> Revert "requirement"

- requirements.txt
Reverts gkn0672/CSIT314-CinemaBookingSystem#64
> Revert "update requirements.txt"

- core/admin.py
- core/models.py
> Movie class added

- core/admin.py
- core/models.py
- Local testing and DB sync check done
- Need to add new classes' table view on admin site 
- Need to create real data , which will be displayed in customer movie detail page for customers
> Prototype for movie, moviesession, cinemaroom done

- DB setup.txt
- core/admin.py
- core/models.py
- Fixed ID error of MovieSession, CinemaRoom, Seat classes
- Fixed admin site view for newly added classes
- Created real 'Movie' class data
- Local testing, DB sync checked
> Subclasses from movie added

- unit_test.py
> test case - 2

- CinemaBooking/settings.py
- UnitTest/test_login.py
- api/urls.py
- When unit test is running, using sqlite3 to test instead of mongoDB
- Unit test data will not affect data inside mongoDB
> Setup enviroment for unit test

- api/checklist.py
- api/commands.py
- api/serializers.py
- api/tempCodeRunnerFile.py
- api/urls.py
- api/views.py
Functions include createProfile, viewProfile, getProfile
> UserProfile class 

- CinemaBooking/settings.py
- CinemaBooking/urls.py
- core/admin.py
- core/models.py
- core/urls.py
- core/views.py
> Added F&B, fixed Img

- UnitTest/test_login.py
- api/serializers.py
- add 'is_active' field to serializer
> Serializer

- api/checklist.py
- api/serializers.py
- api/urls.py
- api/views.py
- core/models.py
just for view all movie image function. so that bh can also get the code and help do tgt. the additions should okay.
> just for view all movie image. so that bh can also get the code and help do tgt.

- UnitTest/test_mov_del.py
- api/checklist.py
- api/serializers.py
- api/urls.py
- api/views.py
> delete and search movie added

- api/urls.py
- api/views.py
add 1 more get movie image function
> getMovieImage v1

- api/checklist.py
- api/urls.py
- api/views.py
> delete movie image, view all movie,

- core/admin.py
- core/models.py
(Not stable) Need to change F&B
> Added Booking class

- core/admin.py
- core/models.py
Deleted 'None' from FnB class , no more needed
> Changed to PurchaseTicket and PurchaseFnB from Booking

- api/serializers.py
- api/urls.py
- api/views.py
- core/admin.py
- core/models.py
> Change img

- api/serializers.py
- api/urls.py
- api/views.py
- core/models.py
not fully tested but just accept so bh can get all the url, serializer and imports from this version
> PurchaseTicket booking, viewAllBook() & addBook() v1

- api/controllers.py
- api/urls.py
do check as well if there are any errors. this one based on my interpretation
> controller class changes 

- api/controllers.py
added 1 more class under movies
> controller class change v4

- core/admin.py
- core/models.py
changed list attributes and price func for consistency
> Changed FnBBooking class

- core/models.py
> Changed FnB field 2

- api/controllers.py
- api/serializers.py
- core/admin.py
- core/models.py
Removed is_available from FnB as well
> Fixed moviebooking attribute error

- api/controllers.py
> viewallfnbBooking edit v1

- api/controllers.py
- core/models.py
> searchfnbBooking correct results v1

- UnitTest/test_cinemaroom_retrieve.py
- UnitTest/test_mov_retrieve.py
- UT for retrieve CR and Movie
> UT for retrieve
